### ISSUE TITLE
Problem Activating Foundation Membership

### ISSUE THREAD

**Issue by eduuh** [dotnet-foundation/membership#90]
![dotfoundation](https://user-images.githubusercontent.com/31909722/107070247-1f50c400-67f4-11eb-8595-62c958893adc.png)

**Comment by shahabfar** [comment]
I had the same problem but it solved by itself. So, try again and the error should be gone.

**Comment by ErcinDedeoglu** [comment]
i have same problem. Also i paid dues but still requesting :/

**Comment by eduuh** [comment]
Thanks, @shahabfar. I logged out of my email address, logged in again, tried and the error was gone.

**Comment by BillWagner** [comment]
Catching up on this thread.

It looks like this has been answered. If not, please add a comment if you're still having issues, I'll track them down.

If there are no further comments, I'll close this at the end of the week.

**Comment by ErcinDedeoglu** [comment]
@BillWagner my problem gone too.
But there is something I am curious about. Although I am included in the monthly payment, the following warning has not been resolved. What should I have done?

![image](https://user-images.githubusercontent.com/6512072/107369210-87ecb900-6af2-11eb-9b67-3bd0cbdf762d.png)

**Comment by seanstride** [comment]
I have also experienced this issue just now when trying to update my profile for the first time.

My request id was: 00-ad4172a6da3c074b8362124f13261068-248776dcd3eece47-00

**Comment by AnassKartit** [comment]
received the same 
Error.
An error occurred while processing your request.
Request ID: 00-884800c448eab042b4724c770c1253a4-6a8bf47d77990041-00

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

**Comment by yinyue200** [comment]
Same issue
After I retried or signed out and retried  The error doesn't gone.


```
An error occurred while processing your request.

Request ID: 00-b9659edb2d12514ab9d17238a84ceed8-72edcbff64963d4e-00
Development Mode

Swapping to Development environment will display more detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

```

**Comment by banditoth** [comment]
Same issue, since yesterday evening.
` Request ID: 00-71bda2e7e6ef0d43b2373be183ddd423-671cc2e6a188f74f-00 `

**Comment by AnassKartit** [comment]
if you would like to access paydues page , you can go to the link https://dotnetfoundation.org/member/profile/PayDues

**Comment by AnassKartit** [comment]
@BillWagner any updates on this?

**Comment by Dushyantsingh-ds** [comment]
When I was trying to activate my membership, there was a Microsoft account login, I tried to select my account and it was showing a error message 

![Screenshot (355)](https://user-images.githubusercontent.com/55306442/126254820-fba74068-ee19-4743-ad15-d29e06006898.png)

after many tries.
I used another account to active that. but face another error message.

![Screenshot (357)](https://user-images.githubusercontent.com/55306442/126254921-01c2631d-a5a8-476f-9ad9-97d3a0d31e9b.png)

I also tried to re-login to my account but the error is the same.

**Comment by WhiteBlackGoose** [comment]
Facing the same issue... `An error occurred while processing your request.`

**Comment by BillWagner** [comment]
You should try an in private window.  The .NET Foundation AAD has issues when there is a LiveID and a Google account in use.

**Comment by WhiteBlackGoose** [comment]
@BillWagner this time it redirected me to google, where I filled in my account password, and then after it redirected me back, it gives the same error

**Comment by manuelvalenzuela** [comment]
Hi @BillWagner, I've tried using private window and still having same issue: "An error occurred while processing your request"
I'm using my google account.
I was able to make my contribution via OpenCollective :)

**Comment by Dushyantsingh-ds** [comment]
Hello @BillWagner, My problem is still the same  "An error occurred while processing your request".

I followed your tricks, but it didn't work.

**Comment by clairernovotny** [comment]
There seems to be an error on the site, I'll take a look very soon.

**Comment by clairernovotny** [comment]
Can you please try again, this should be fixed now.

**Comment by manuelvalenzuela** [comment]
Hi @clairernovotny, thank you for looking into this. Unfortunately I'm having same issue, I'm trying with this URL:
https://dotnetfoundation.org/member/profile

thanks
Manuel

**Comment by clairernovotny** [comment]
Cah you please try again? Looks like an underlying library changed behavior. Should be fixed now.

**Comment by Serg046** [comment]
Thank you Claire, it is working now!

**Comment by Perksey** [comment]
I still can't get past the AAD screen! When logging in using "Sign in with GitHub" I get presented with this "not in tenant" error.

**Comment by manuelvalenzuela** [comment]
It worked for me @clairernovotny! thank you so much!

**Comment by nicoleabuhakmeh** [comment]
This website is no longer.
